DROP DATABASE IF EXISTS USUARIOAES;
CREATE DATABASE USUARIOAES;
USE USUARIOAES;
CREATE TABLE USUARIO(
	id_usu int PRIMARY KEY AUTO_INCREMENT,
	nom_usu VARCHAR(45) NOT NULL
	ema_usu VARCHAR(45) NOT NULL,
	pass_usu VARCHAR(45) NOT NULL,
	tel_usu int NOT NULL
);
