DROP DATABASE IF EXISTS USUARIOAES;
CREATE DATABASE USUARIOAES;
USE USUARIOAES;
CREATE TABLE USUARIO(
	id_usu int PRIMARY KEY AUTO_INCREMENT,
	nom_usu VARCHAR(100) NOT NULL,
	ema_usu VARCHAR(100) NOT NULL,
	edad_usu VARCHAR(100) NOT NULL,
	tel_usu  VARCHAR(100)NOT NULL
);
