DROP DATABASE IF EXISTS EXAMENCIFRADO;
CREATE DATABASE EXAMENCIFRADO;
USE EXAMEN;
CREATE TABLE USUARIO(
	id_user int primary key AUTO_INCREMENT,
	nombre 	VARCHAR(100) NOT NULL,
	password VARCHAR(50) NOT NULL
);
CREATE TABLE REPORTE(
	id_reporte int PRIMARY KEY AUTO_INCREMENT,
	id_user  int NOT NULL,  
	cuerpo VARCHAR(100) NOT NULL,
	fec_rep DATE NOT NULL,
	FOREIGN KEY (id_user) REFERENCES USUARIO(id_user)     
);
INSERT INTO USUARIO VALUES(nombre,password)
('mauricio','contraseña');